update

diff --git a/packages/foundry/Makefile b/packages/foundry/Makefile
--- a/packages/foundry/Makefile
+++ b/packages/foundry/Makefile
@@ -17,8 +17,19 @@ fork: setup-anvil-wallet
 
 # Deploy the contracts
 deploy:
-	@if [ ! -f "$(DEPLOY_SCRIPT)" ]; then 		echo "Error: Deploy script '$(DEPLOY_SCRIPT)' not found"; 		exit 1; 	fi
-	@if [ "$(RPC_URL)" = "localhost" ]; then 		if [ "$(ETH_KEYSTORE_ACCOUNT)" = "scaffold-eth-default" ]; then 			forge script $(DEPLOY_SCRIPT) --rpc-url localhost --password localhost --broadcast --legacy --ffi; 		else 			forge script $(DEPLOY_SCRIPT) --rpc-url localhost --broadcast --legacy --ffi; 		fi 	else 		forge script $(DEPLOY_SCRIPT) --rpc-url $(RPC_URL) --broadcast --legacy --ffi; 	fi
+	@if [ ! -f "$(DEPLOY_SCRIPT)" ]; then \
+		echo "Error: Deploy script '$(DEPLOY_SCRIPT)' not found"; \
+		exit 1; \
+	fi
+	@if [ "$(RPC_URL)" = "localhost" ]; then \
+		if [ "$(ETH_KEYSTORE_ACCOUNT)" = "scaffold-eth-default" ]; then \
+			forge script $(DEPLOY_SCRIPT):DeployScript --rpc-url localhost --password localhost --broadcast --legacy --ffi; \
+		else \
+			forge script $(DEPLOY_SCRIPT):DeployScript --rpc-url localhost --broadcast --legacy --ffi; \
+		fi \
+	else \
+		forge script $(DEPLOY_SCRIPT):DeployScript --rpc-url $(RPC_URL) --broadcast --legacy --ffi; \
+	fi
 
 # Deploy and generate ABIs
 deploy-and-generate-abis: deploy generate-abis 
